name: Commandy
author: Turqmelon
version: 1.0
main: com.turqmelon.Commandy.Commandy
description: General commands and server utilities.
commands:
  item:
    usage: /item
    description: Give yourself (or someone else) an item
    aliases: [i, give]
  more:
    usage: /more
    description: Give more of an item
    alises: [more, stack]
  who:
    usage: /who
    aliases: [who, list, online, players, playerlist]
  motd:
    usage: /motd
  rules:
    usage: /rules
  kit:
    usage: /kit